# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: "Rice Fields"
tagline: "A blog dedicated to by hobbies and interests."
description: "Hello there! I am rice who loves computers in a vast field of ricefields."
url: https://ricefields.me
#baseurl:          '/blog'
# the optional subpath of your site, e.g. "/blog"
# NB: This applies to all pages in your Jekyll site.
# If you want to move just the blog index pages but keep
# other pages at root, see the paginate_path and
# sidebar_blog_link below.

author:
  name: RiceFields
  url: https://twitter.com/RiceNFields

paginate: 5
# paginate_path:    '/page:num'
# Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator: <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link: true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
# page. If you change your paginate_path,
# set this to the root of the paginate_path
# to enable a separate blog link.

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.
hydeout:
  version: 4.2.0
  repo: https://github.com/RiceNFields
  twitter: https://twitter.com/RiceNFields
  email: ashishbhattarai@protonmail.com

# SEO config
twitter:
  username: RiceNFields
  card: summary

logo: "/android-chrome-512x512.png"
